nico-api:
  resources:
    limits:
      cpu: "16"
      memory: "16Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  siteConfig:
    enabled: true
    nicoApiSiteConfig: |
      bypass_rbac = true
      attestation_enabled = false
      dpu_ipmi_tool_impl = "test"
      initial_domain_name = "local.nico"
      initial_dpu_agent_upgrade_policy = "off"

      # DB transactions in nico should be quick, pool size should ≈ the
      # number of cores. Default postgres configuration is a 100 connection
      # limit, so let's stay safely below that.
      max_database_connections = 64

      [pools.lo-ip]
      type = "ipv4"
      ranges = [{ start = "10.180.64.1", end = "10.180.127.254" }]

      [pools.vlan-id]
      type = "integer"
      ranges = [{ start = "100", end = "501" }]

      [pools.vni]
      type = "integer"
      ranges = [{ start = "1024500", end = "1024550" }]

      [pools.vpc-vni]
      type = "integer"
      ranges = [{ start = "2024500", end = "2024550" }]

      [pools.fnn-asn]
      type = "integer"
      ranges = [{ start = "1000", end = "10000" }]

      [networks.admin]
      type = "admin"
      prefix = "192.168.64.0/18"
      gateway = "192.168.64.1"
      mtu = 9000
      reserve_first = 2

      [networks.DEV-K3S-DPU-ACORN-0]
      type = "underlay"
      prefix = "192.168.128.0/18"
      gateway = "192.168.128.1"
      mtu = 1500
      reserve_first = 2

      [networks.DEV-K3S-X86-BMC-UNDERLAY-ACORN-X86-0]
      type = "underlay"
      prefix = "192.168.192.0/18"
      gateway = "192.168.192.1"
      mtu = 1500
      reserve_first = 2

      [auth]
      permissive_mode = true

      [auth.trust]
      spiffe_trust_domain = "nico.local"
      spiffe_service_base_paths = ["/nico-system/sa/", "/default/sa/"]
      spiffe_machine_base_path = "/nico-system/machine/"
      additional_issuer_cns = []

      [host_health]
      hardware_health_reports = "MonitorOnly"

      [machine_state_controller]
      dpu_wait_time = "1s"
      skip_polling_checks = true

      [machine_state_controller.controller]
      iteration_time = "30s"
      max_concurrency = 100

      [machine_validation_config]
      enabled = false

      [bios_profiles.Cisco.CAI-845A-M8.performance]
      NWSK000 = "Enabled"
      NWSK001 = "Enabled"
      NWSK006 = "Enabled"
      NWSK002 = "Disabled"
      NWSK007 = "Disabled"

      [bios_profiles.Cisco.CAI-885A-M8.performance]
      NWSK000 = "Enabled"
      NWSK001 = "Enabled"
      NWSK006 = "Enabled"
      NWSK002 = "Disabled"
      NWSK007 = "Disabled"

      [host_models.cisco_c845a_m8]
      vendor = "Cisco"
      model = "CAI-845A-M8"
      ordering = ["uefi", "bmc"]

      [host_models.cisco_c845a_m8.components.bmc]
      current_version_reported_as = ".*bmc.*"
      preingest_upgrade_when_below = "0.0"

      [host_models.cisco_c845a_m8.components.uefi]
      current_version_reported_as = ".*bios.*"
      preingest_upgrade_when_below = "0.0"

      [host_models.cisco_c885a_m8]
      vendor = "Cisco"
      model = "CAI-885A-M8"
      ordering = ["uefi", "bmc"]

      [host_models.cisco_c885a_m8.components.bmc]
      current_version_reported_as = ".*bmc.*"
      preingest_upgrade_when_below = "0.0"

      [host_models.cisco_c885a_m8.components.uefi]
      current_version_reported_as = ".*bios.*"
      preingest_upgrade_when_below = "0.0"

      [host_models.cisco_ucs_ami]
      vendor = "Cisco"
      model = "CAI-*-M8"
      ordering = ["uefi", "bmc"]

      [host_models.cisco_ucs_ami.components.bmc]
      current_version_reported_as = ".*bmc.*"
      preingest_upgrade_when_below = "0.0"

      [host_models.cisco_ucs_ami.components.uefi]
      current_version_reported_as = ".*bios.*"
      preingest_upgrade_when_below = "0.0"

      [site_explorer]
      enabled = true
      create_machines = true
      allow_changing_bmc_proxy = true
      allow_zero_dpu_hosts = true
      bmc_proxy = "machine-a-tron-bmc-mock.nico-system.svc.cluster.local:1266"
      run_interval = "10s"
      machines_created_per_run = 1000
      explorations_per_run = 1000
      concurrent_explorations = 100
      explore_mode = "nv-redfish"

      [firmware_global]
      autoupdate = true
      run_interval = "10s"
      concurrency_limit = 100

nico-bmc-proxy:
  enabled: true
  replicas: 1 # save on local resources
  configFiles:
    enabled: true
    nicoBmcProxyConfig: |
      listen = "[::]:1079"
      metrics_endpoint = "[::]:1080"
      database_url = "postgres://replaced-by-env-var"
      allowed_principals = ["trusted-certificate"]
      bmc_proxy = "machine-a-tron-bmc-mock.nico-system.svc.cluster.local:1266"

      [tls]
      identity_pemfile_path = "/var/run/secrets/spiffe.io/tls.crt"
      identity_keyfile_path = "/var/run/secrets/spiffe.io/tls.key"
      root_cafile_path = "/var/run/secrets/spiffe.io/ca.crt"
      admin_root_cafile_path = "/etc/forge/carbide-bmc-proxy/site/admin_root_cert_pem"

      [auth.trust]
      spiffe_trust_domain = "nico.local"
      spiffe_service_base_paths = [
        "/nico-system/sa/",
        "/default/sa/",
      ]
      spiffe_machine_base_path = "/nico-system/machine/"
      additional_issuer_cns = []

      [auth.acls]
      "trusted-certificate" = ["/**"]

      [carbide_api]
      api_url = "https://nico-api.nico-system.svc.cluster.local:1079"
      root_ca = "/var/run/secrets/spiffe.io/ca.crt"
      client_cert = "/var/run/secrets/spiffe.io/tls.crt"
      client_key = "/var/run/secrets/spiffe.io/tls.key"

nico-dhcp:
  enabled: false
nico-dns:
  enabled: false
nico-dsx-exchange-consumer:
  enabled: false
nico-hardware-health:
  enabled: false
nico-pxe:
  enabled: false
nico-ssh-console-rs:
  enabled: false
unbound:
  enabled: false
